/**
 * Achievement definitions (mirror src/constants/achievements for mobile).
 */

export interface AchievementDefinition {
  id: string;
  code: string;
  name_sv: string;
  name_en: string;
  description_sv: string;
  description_en: string;
  icon: string;
  points: number;
  category: "profile" | "matching" | "chat" | "personality" | "social";
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  {
    id: "profile_complete",
    code: "profile_complete",
    name_sv: "Profilmästare",
    name_en: "Profile Master",
    description_sv: "Fyll i din profil helt",
    description_en: "Complete your profile",
    icon: "👤",
    category: "profile",
    points: 10,
  },
  {
    id: "first_match",
    code: "first_match",
    name_sv: "Första matchningen",
    name_en: "First Match",
    description_sv: "Få din första match",
    description_en: "Get your first match",
    icon: "💕",
    category: "matching",
    points: 20,
  },
  {
    id: "first_message",
    code: "first_message",
    name_sv: "Isbrytare",
    name_en: "Icebreaker",
    description_sv: "Skicka ditt första meddelande",
    description_en: "Send your first message",
    icon: "💬",
    category: "chat",
    points: 15,
  },
  {
    id: "personality_test",
    code: "personality_test",
    name_sv: "Självkännedom",
    name_en: "Self-Awareness",
    description_sv: "Genomför personlighetstestet",
    description_en: "Complete the personality test",
    icon: "🧠",
    category: "personality",
    points: 25,
  },
  {
    id: "photo_upload",
    code: "photo_upload",
    name_sv: "Fotogen",
    name_en: "Photogenic",
    description_sv: "Ladda upp ett profilfoto",
    description_en: "Upload a profile photo",
    icon: "📷",
    category: "profile",
    points: 10,
  },
  {
    id: "weekly_active",
    code: "weekly_active",
    name_sv: "Veckoaktiv",
    name_en: "Weekly Active",
    description_sv: "Logga in varje dag i en vecka",
    description_en: "Log in every day for a week",
    icon: "🔥",
    category: "social",
    points: 30,
  },
  {
    id: "conversation_starter",
    code: "conversation_starter",
    name_sv: "Konversationsstartare",
    name_en: "Conversation Starter",
    description_sv: "Starta 5 konversationer",
    description_en: "Start 5 conversations",
    icon: "🗣️",
    category: "chat",
    points: 25,
  },
  {
    id: "perfect_match",
    code: "perfect_match",
    name_sv: "Perfekt Match",
    name_en: "Perfect Match",
    description_sv: "Få en match med 95%+ kompatibilitet",
    description_en: "Get a match with 95%+ compatibility",
    icon: "💯",
    category: "matching",
    points: 50,
  },
  {
    id: "id_verified",
    code: "id_verified",
    name_sv: "Verifierad",
    name_en: "Verified",
    description_sv: "Verifiera din identitet med ID",
    description_en: "Verify your identity with ID",
    icon: "🪪",
    category: "profile",
    points: 15,
  },
  // ── Nya MÄÄK-anpassade prestationer (Fas 2) ──
  {
    id: "daily_icebreaker",
    code: "daily_icebreaker",
    name_sv: "Isbrytaren",
    name_en: "The Icebreaker",
    description_sv: "Skicka en AI-isbrytare till en matchning",
    description_en: "Send an AI icebreaker to a match",
    icon: "❄️",
    category: "chat",
    points: 10,
  },
  {
    id: "group_creator",
    code: "group_creator",
    name_sv: "Samlaren",
    name_en: "The Gatherer",
    description_sv: "Skapa din första samlingsgrupp",
    description_en: "Create your first samlingsgrupp",
    icon: "🌿",
    category: "social",
    points: 20,
  },
  {
    id: "group_joiner",
    code: "group_joiner",
    name_sv: "Medresenären",
    name_en: "Fellow Traveler",
    description_sv: "Gå med i 3 samlingsgrupper",
    description_en: "Join 3 samlingsgrupper",
    icon: "🤝",
    category: "social",
    points: 15,
  },
  {
    id: "deep_conversation",
    code: "deep_conversation",
    name_sv: "Djupdykaren",
    name_en: "Deep Diver",
    description_sv: "Ha en konversation med 20+ meddelanden",
    description_en: "Have a conversation with 20+ messages",
    icon: "🌊",
    category: "chat",
    points: 25,
  },
  {
    id: "weekly_matcher",
    code: "weekly_matcher",
    name_sv: "Veckomatcharen",
    name_en: "Weekly Matcher",
    description_sv: "Få matchningar 7 dagar i rad",
    description_en: "Receive matches 7 days in a row",
    icon: "📅",
    category: "matching",
    points: 30,
  },
  {
    id: "personality_explorer",
    code: "personality_explorer",
    name_sv: "Personlighetsguiden",
    name_en: "Personality Guide",
    description_sv: "Läs om alla 4 personlighetskategorier",
    description_en: "Read about all 4 personality categories",
    icon: "🧭",
    category: "personality",
    points: 15,
  },
  {
    id: "photo_pro",
    code: "photo_pro",
    name_sv: "Fotoproffset",
    name_en: "Photo Pro",
    description_sv: "Ladda upp 4+ profilfoton",
    description_en: "Upload 4+ profile photos",
    icon: "📸",
    category: "profile",
    points: 10,
  },
  {
    id: "sunday_rematcher",
    code: "sunday_rematcher",
    name_sv: "Söndagshjälten",
    name_en: "Sunday Hero",
    description_sv: "Använd söndagsmatchning och chatta med en match",
    description_en: "Use Sunday Rematch and chat with a match",
    icon: "☀️",
    category: "matching",
    points: 20,
  },
  {
    id: "bio_writer",
    code: "bio_writer",
    name_sv: "Berättaren",
    name_en: "The Storyteller",
    description_sv: "Skriv en bio med 100+ tecken",
    description_en: "Write a bio with 100+ characters",
    icon: "✍️",
    category: "profile",
    points: 10,
  },
  {
    id: "multi_chatter",
    code: "multi_chatter",
    name_sv: "Samtalsmästaren",
    name_en: "Chat Champion",
    description_sv: "Ha aktiva chattar med 5+ matchningar",
    description_en: "Have active chats with 5+ matches",
    icon: "💬",
    category: "chat",
    points: 25,
  },
];

export function getLocalizedAchievement(
  definition: AchievementDefinition,
  locale: string,
): { name: string; description: string } {
  const isSwedish = locale.startsWith("sv");
  return {
    name: isSwedish ? definition.name_sv : definition.name_en,
    description: isSwedish ? definition.description_sv : definition.description_en,
  };
}
