name: Create Preview Builds

on:
  push:
    branches: ['develop']

jobs:
  build_ios:
    type: build
    params:
      platform: ios
      profile: preview
  build_android:
    type: build
    params:
      platform: android
      profile: preview
