
# Custom job
#
# This workflow shows how to write custom jobs.
# It contains a predefined workflow step and a shell command to print "Hello, World!".
#
# Key features:
# - Triggers on pushes to the main branch.
#    (Requires linked GitHub account: https://expo.dev/accounts/[account]/settings/github)
# - Can be triggered manually with eas workflow:run custom.yml
# - Runs eas/checkout then a custom "echo" command
#
# For detailed documentation on workflow syntax and available step types, visit:
# https://docs.expo.dev/eas/workflows/syntax/#jobsjob_idstepsstepuses
#
# Created by EAS CLI v18.1.0
#

name: Custom workflow
on:
  push:
    branches:
      - main
jobs:
  custom_build:
    name: Custom job
    steps:
      - uses: eas/checkout
      - name: Hello World
        id: hello_world
        run: |
          # Custom script
          echo "Hello, World"
