
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables
const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID || '';
const SUPABASE_URL_ENV = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Construct Supabase URL from project ID if URL is not provided
function getSupabaseUrl(): string {
  // If URL is explicitly provided and valid, use it
  if (SUPABASE_URL_ENV && 
      SUPABASE_URL_ENV.startsWith('https://') && 
      SUPABASE_URL_ENV.includes('.supabase.co') &&
      !SUPABASE_URL_ENV.includes('your_project') &&
      !SUPABASE_URL_ENV.includes('placeholder')) {
    return SUPABASE_URL_ENV;
  }

  // Try to construct from project ID
  if (SUPABASE_PROJECT_ID && 
      !SUPABASE_PROJECT_ID.includes('your_project') &&
      !SUPABASE_PROJECT_ID.includes('placeholder')) {
    return `https://${SUPABASE_PROJECT_ID}.supabase.co`;
  }

  // Fallback to empty string (will be handled by validation)
  return '';
}

const SUPABASE_URL = getSupabaseUrl();

// Validate environment variables
const isValidUrl = SUPABASE_URL && 
  SUPABASE_URL.startsWith('https://') && 
  SUPABASE_URL.includes('.supabase.co') &&
  !SUPABASE_URL.includes('your_project') &&
  !SUPABASE_URL.includes('placeholder');

const isValidKey = SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_PUBLISHABLE_KEY.length > 20 &&
  !SUPABASE_PUBLISHABLE_KEY.includes('your_anon') &&
  !SUPABASE_PUBLISHABLE_KEY.includes('your-anon') &&
  !SUPABASE_PUBLISHABLE_KEY.includes('placeholder');

if (!isValidUrl || !isValidKey) {
  const missing = [];
  if (!isValidUrl) missing.push('VITE_SUPABASE_URL or VITE_SUPABASE_PROJECT_ID');
  if (!isValidKey) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  
  console.error(
    `⚠️ Supabase configuration error: Missing or invalid ${missing.join(' and ')}.\n` +
    `Please set these in your .env file with real values from https://supabase.com/dashboard → Settings → API`
  );
}

// Export the URL for use in other parts of the app
export const SUPABASE_URL_EXPORT = SUPABASE_URL;

// Allow app to load without Supabase so /demo-seed and landing work when .env is missing
const isTestEnv = typeof process !== 'undefined' && process.env?.NODE_ENV === 'test';
const allowPlaceholders = isTestEnv || import.meta.env.VITE_ALLOW_PLACEHOLDER_SUPABASE === 'true';
const hasValidConfig = isValidUrl && isValidKey;

if (!hasValidConfig) {
  if (!allowPlaceholders) {
    console.warn(
      'Supabase configuration is missing or invalid. The app will load but login and data features will not work. ' +
      'Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env to enable them. ' +
      'You can still use the demo at /demo-seed.'
    );
  }
}

// Use placeholder URL/key when invalid so createClient doesn't throw; real requests will fail until .env is set
const urlForClient = hasValidConfig ? SUPABASE_URL : `https://placeholder.supabase.co`;
const keyForClient = hasValidConfig ? SUPABASE_PUBLISHABLE_KEY : 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.placeholder';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  urlForClient,
  keyForClient,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);