
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables (support both current and legacy names)
const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID || '';
const SUPABASE_URL_ENV = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  '';

// Construct Supabase URL from project ID if URL is not provided
function getSupabaseUrl(): string {
  // If URL is explicitly provided and valid, use it
  if (SUPABASE_URL_ENV && 
      SUPABASE_URL_ENV.startsWith('https://') && 
      SUPABASE_URL_ENV.includes('.supabase.co') &&
      !SUPABASE_URL_ENV.includes('your_project') &&
      !SUPABASE_URL_ENV.includes('placeholder')) {
    return SUPABASE_URL_ENV;
  }

  // Try to construct from project ID
  if (SUPABASE_PROJECT_ID && 
      !SUPABASE_PROJECT_ID.includes('your_project') &&
      !SUPABASE_PROJECT_ID.includes('placeholder')) {
    return `https://${SUPABASE_PROJECT_ID}.supabase.co`;
  }

  // Fallback to empty string (will be handled by validation)
  return '';
}

const SUPABASE_URL = getSupabaseUrl();

// Validate environment variables
const isValidUrl = SUPABASE_URL && 
  SUPABASE_URL.startsWith('https://') && 
  SUPABASE_URL.includes('.supabase.co') &&
  !SUPABASE_URL.includes('your_project') &&
  !SUPABASE_URL.includes('placeholder');

const isValidKey = SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_PUBLISHABLE_KEY.length > 20 &&
  !SUPABASE_PUBLISHABLE_KEY.includes('your_anon') &&
  !SUPABASE_PUBLISHABLE_KEY.includes('your-anon') &&
  !SUPABASE_PUBLISHABLE_KEY.includes('placeholder');

if (!isValidUrl || !isValidKey) {
  const missing = [];
  if (!isValidUrl) missing.push('VITE_SUPABASE_URL or VITE_SUPABASE_PROJECT_ID');
  if (!isValidKey) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  
  console.warn(
    `Supabase: missing or invalid ${missing.join(' and ')}. Set them in .env from Supabase Dashboard → Settings → API. Demo at /demo-seed works without them.`
  );
}

const hasValidConfig = isValidUrl && isValidKey;

/** True when .env has valid Supabase URL and key. Use to show setup page instead of app when false. */
export const SUPABASE_CONFIGURED = hasValidConfig;
export const hasValidSupabaseConfig = hasValidConfig;

// Export the URL for use in other parts of the app
export const SUPABASE_URL_EXPORT = SUPABASE_URL;

if (!hasValidConfig) {
  console.warn(
    '[MÄÄK] Supabase not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env. Demo: /demo-seed.'
  );
}

// Use placeholder when invalid so createClient doesn't throw; app can show setup page
const urlForClient = hasValidConfig ? SUPABASE_URL : 'https://placeholder.supabase.co';
const keyForClient = hasValidConfig ? SUPABASE_PUBLISHABLE_KEY : 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.placeholder';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  urlForClient,
  keyForClient,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);