
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables from process.env only (works in both Vite and Metro/Hermes).
// Vite build injects VITE_* via define in vite.config; Metro/EAS use EXPO_PUBLIC_*.
const getEnv = (viteKey: string, expoKey: string): string => {
  const env = typeof process !== 'undefined' ? process.env : undefined;
  if (!env) return '';
  return (env as Record<string, string>)[expoKey] ?? (env as Record<string, string>)[viteKey] ?? '';
};
const SUPABASE_PROJECT_ID = getEnv('VITE_SUPABASE_PROJECT_ID', 'EXPO_PUBLIC_SUPABASE_PROJECT_ID') || '';
const SUPABASE_URL_ENV = getEnv('VITE_SUPABASE_URL', 'EXPO_PUBLIC_SUPABASE_URL') || '';
const SUPABASE_PUBLISHABLE_KEY =
  getEnv('VITE_SUPABASE_PUBLISHABLE_KEY', 'EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY') ||
  getEnv('VITE_SUPABASE_ANON_KEY', 'EXPO_PUBLIC_SUPABASE_ANON_KEY') ||
  '';

// Construct Supabase URL from project ID if URL is not provided
function getSupabaseUrl(): string {
  // If URL is explicitly provided and valid, use it
  if (SUPABASE_URL_ENV && 
      SUPABASE_URL_ENV.startsWith('https://') && 
      SUPABASE_URL_ENV.includes('.supabase.co') &&
      !SUPABASE_URL_ENV.includes('your_project') &&
      !SUPABASE_URL_ENV.includes('placeholder')) {
    return SUPABASE_URL_ENV;
  }

  // Try to construct from project ID
  if (SUPABASE_PROJECT_ID && 
      !SUPABASE_PROJECT_ID.includes('your_project') &&
      !SUPABASE_PROJECT_ID.includes('placeholder')) {
    return `https://${SUPABASE_PROJECT_ID}.supabase.co`;
  }

  // Fallback to empty string (will be handled by validation)
  return '';
}

const SUPABASE_URL = getSupabaseUrl();

// Validate environment variables
const isValidUrl = SUPABASE_URL && 
  SUPABASE_URL.startsWith('https://') && 
  SUPABASE_URL.includes('.supabase.co') &&
  !SUPABASE_URL.includes('your_project') &&
  !SUPABASE_URL.includes('placeholder');

const isValidKey = SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_PUBLISHABLE_KEY.length > 20 &&
  !SUPABASE_PUBLISHABLE_KEY.includes('your_anon') &&
  !SUPABASE_PUBLISHABLE_KEY.includes('your-anon') &&
  !SUPABASE_PUBLISHABLE_KEY.includes('placeholder');

const isDev = typeof process !== 'undefined' && process.env?.NODE_ENV === 'development';
if (isDev && (!isValidUrl || !isValidKey)) {
  const missing = [];
  if (!isValidUrl) missing.push('VITE_SUPABASE_URL or VITE_SUPABASE_PROJECT_ID');
  if (!isValidKey) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  console.warn(
    `Supabase: missing or invalid ${missing.join(' and ')}. Set them in .env from Supabase Dashboard → Settings → API. Demo at /demo-seed works without them.`
  );
}

const hasValidConfig = isValidUrl && isValidKey;

/** True when .env has valid Supabase URL and key. Use to show setup page instead of app when false. */
export const SUPABASE_CONFIGURED = hasValidConfig;
export const hasValidSupabaseConfig = hasValidConfig;

// Export the URL for use in other parts of the app
export const SUPABASE_URL_EXPORT = SUPABASE_URL;

if (isDev && !hasValidConfig) {
  console.warn(
    '[MÄÄK] Supabase not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env. Demo: /demo-seed.'
  );
}

// Use placeholder when invalid so createClient doesn't throw; app can show setup page
const urlForClient = hasValidConfig ? SUPABASE_URL : 'https://placeholder.supabase.co';
const keyForClient = hasValidConfig ? SUPABASE_PUBLISHABLE_KEY : 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.placeholder';

// Auth storage: use localStorage on web/Capacitor; in Expo Go (React Native) use in-memory fallback
const memoryStorage: Record<string, string> = {};
const authStorage =
  typeof localStorage !== 'undefined'
    ? localStorage
    : {
        getItem: (key: string) => (key in memoryStorage ? memoryStorage[key] : null),
        setItem: (key: string, value: string) => { memoryStorage[key] = value; },
        removeItem: (key: string) => { delete memoryStorage[key]; },
      };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  urlForClient,
  keyForClient,
  {
    auth: {
      storage: authStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);